### ISSUE TITLE
npm install: Error: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by loretoparisi** [mbejda/Nodejs-Stanford-Classifier#3]
```
$ npm install stanford-classifier --save
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> java@0.6.0 install /my-app/node_modules/java
> node-gyp rebuild

2016-11-22 18:37:31.966 xcodebuild[68190:16069135] [MT] PluginLoading: Required plug-in compatibility UUID DA4FDFD8-C509-4D8B-8B55-84A7B66AE701 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
../node_modules/nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/nodejavabridge_bindings/src/java.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /my-app/node_modules/java
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "stanford-classifier" "--save"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! java@0.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the java@0.6.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs java
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.
```

I'm running

```
$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

on `macOS Sierra 10.12.11`

**Comment by loretoparisi** [comment]
I think this is related to `node-java` so I have opened there: https://github.com/joeferner/node-java/issues/368

**Comment by mbejda** [comment]
@loretoparisi  I did experience similar issue with node-java and the latest `nodejs` version. Try downgrading your Node.

**Comment by loretoparisi** [comment]
@mbejda digging around this seems the issue. I have

```
   $ n
  
   node/4.2.6
    node/4.4.0
    node/5.4.1
    node/5.5.0
  ο node/6.3.0

```

Problem is that I'm using all ECMAScript6 syntax/operators like arrow, spread, Map, class, etc, so my minimal required version should be `node/5.4.1` a I guess (to be verified). Which version are you running?

...just realized that using `let` will lock me to `node6` 🎱 

```
                    let contents = data.Body.toString('utf-8'); // Use the encoding necessary
                    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

unless I put `strict` everywhere, and hopefully it works or move to `ubuntu`.

**Comment by loretoparisi** [comment]
**[UPDATE]**

So I had to switch to 

```
    node/0.12.9
    node/4.2.6
    node/4.4.0
    node/5.4.1
  ο node/5.5.0
    node/6.3.0
```

this caused me to use `strict` mode for any `let` operator, but it worked!

```
$ npm install stanford-classifier --save

> java@0.6.0 install /my-project/node_modules/java
> node-gyp rebuild

2016-11-23 15:00:26.069 xcodebuild[12416:17550642] [MT] PluginLoading: Required plug-in compatibility UUID DA4FDFD8-C509-4D8B-8B55-84A7B66AE701 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/javaObject.o
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/javaScope.o
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/methodCallBaton.o
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/nodeJavaBridge.o
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/utils.o
  SOLINK_MODULE(target) Release/nodejavabridge_bindings.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9

> java@0.6.0 postinstall /my-project/node_modules/java
> node postInstall.js

/my-project
└─┬ stanford-classifier@2.0.0 
  └─┬ java@0.6.0 
    ├── async@0.9.0 
    ├─┬ find-java-home@0.1.2 
    │ └── which@1.0.9 
    ├─┬ glob@5.0.5 
    │ └── minimatch@2.0.10 
    ├── lodash@3.7.0 
    └── nan@2.0.9 

```

**Comment by loretoparisi** [comment]
Closing this since it seems to work with `node/5.5.0`.
