### ISSUE TITLE
error: no member named 'SetHiddenValue' in 'v8::Object'

### ISSUE THREAD

**Issue by gectus** [mbejda/Nodejs-Stanford-Classifier#7]
Hi
I can't install Nodejs-Stanford-Classifier on Mac :(

```
node --version
v7.10.0
```

```
cat package.json 
{
  "name": "message-classifier",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng"
  },
  "private": true,
  "dependencies": {
    "node-java": "^1.0.1",
    "stanford-classifier": "^2.0.1"
  }
}
```

```
rm -rf node_modules && npm i

> java@0.7.2 install /Users/grin/message-classifier/node_modules/java
> node-gyp rebuild

  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
In file included from ../../nan/nan.h:196:
../../nan/nan_maybe_43_inl.h:220:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]
  return array->CloneElementAt(GetCurrentContext(), index);
                ^
/Users/grin/.node-gyp/7.10.0/include/node/v8.h:3347:36: note: 'CloneElementAt' has been explicitly marked deprecated here
                MaybeLocal<Object> CloneElementAt(Local<Context> context,
                                   ^
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                            ^
/Users/grin/.node-gyp/7.10.0/include/node/v8.h:4490:56: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                       ^
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
../../nan/nan.h:2017:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
  return obj->SetAccessor(
              ^
/Users/grin/.node-gyp/7.10.0/include/node/v8.h:3027:22: note: 'SetAccessor' has been explicitly marked deprecated here
                bool SetAccessor(Local<Name> name,
                     ^
../src/java.cpp:897:40: warning: 'ToNumber' is deprecated [-Wdeprecated-declarations]
  v8::Local<v8::Number> val = info[0]->ToNumber();
                                       ^
/Users/grin/.node-gyp/7.10.0/include/node/v8.h:9005:22: note: 'ToNumber' has been explicitly marked deprecated here
Local<Number> Value::ToNumber() const {
                     ^
../src/java.cpp:927:40: warning: 'ToNumber' is deprecated [-Wdeprecated-declarations]
  v8::Local<v8::Number> val = info[0]->ToNumber();
                                       ^
/Users/grin/.node-gyp/7.10.0/include/node/v8.h:9005:22: note: 'ToNumber' has been explicitly marked deprecated here
Local<Number> Value::ToNumber() const {
                     ^
../src/java.cpp:956:40: warning: 'ToNumber' is deprecated [-Wdeprecated-declarations]
  v8::Local<v8::Number> val = info[0]->ToNumber();
                                       ^
/Users/grin/.node-gyp/7.10.0/include/node/v8.h:9005:22: note: 'ToNumber' has been explicitly marked deprecated here
Local<Number> Value::ToNumber() const {
                     ^
../src/java.cpp:983:42: warning: 'ToNumber' is deprecated [-Wdeprecated-declarations]
    v8::Local<v8::Number> val = info[0]->ToNumber();
                                         ^
/Users/grin/.node-gyp/7.10.0/include/node/v8.h:9005:22: note: 'ToNumber' has been explicitly marked deprecated here
Local<Number> Value::ToNumber() const {
                     ^
../src/java.cpp:1019:40: warning: 'ToNumber' is deprecated [-Wdeprecated-declarations]
  v8::Local<v8::Number> val = info[0]->ToNumber();
                                       ^
/Users/grin/.node-gyp/7.10.0/include/node/v8.h:9005:22: note: 'ToNumber' has been explicitly marked deprecated here
Local<Number> Value::ToNumber() const {
                     ^
../src/java.cpp:1044:40: warning: 'ToNumber' is deprecated [-Wdeprecated-declarations]
  v8::Local<v8::Number> val = info[0]->ToNumber();
                                       ^
/Users/grin/.node-gyp/7.10.0/include/node/v8.h:9005:22: note: 'ToNumber' has been explicitly marked deprecated here
Local<Number> Value::ToNumber() const {
                     ^
../src/java.cpp:1263:16: warning: 'TryCatch' is deprecated [-Wdeprecated-declarations]
  v8::TryCatch tryCatch;
               ^
/Users/grin/.node-gyp/7.10.0/include/node/v8.h:7616:40: note: 'TryCatch' has been explicitly marked deprecated here
  V8_DEPRECATED("Use isolate version", TryCatch());
                                       ^
10 warnings generated.
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/javaObject.o
In file included from ../src/javaObject.cpp:1:
In file included from ../src/javaObject.h:10:
In file included from ../src/methodCallBaton.h:5:
In file included from ../src/utils.h:12:
In file included from ../../nan/nan.h:196:
../../nan/nan_maybe_43_inl.h:220:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]
  return array->CloneElementAt(GetCurrentContext(), index);
                ^
/Users/grin/.node-gyp/7.10.0/include/node/v8.h:3347:36: note: 'CloneElementAt' has been explicitly marked deprecated here
                MaybeLocal<Object> CloneElementAt(Local<Context> context,
                                   ^
In file included from ../src/javaObject.cpp:1:
In file included from ../src/javaObject.h:10:
In file included from ../src/methodCallBaton.h:5:
In file included from ../src/utils.h:12:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                            ^
/Users/grin/.node-gyp/7.10.0/include/node/v8.h:4490:56: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                       ^
In file included from ../src/javaObject.cpp:1:
In file included from ../src/javaObject.h:10:
In file included from ../src/methodCallBaton.h:5:
In file included from ../src/utils.h:12:
../../nan/nan.h:2017:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
  return obj->SetAccessor(
              ^
/Users/grin/.node-gyp/7.10.0/include/node/v8.h:3027:22: note: 'SetAccessor' has been explicitly marked deprecated here
                bool SetAccessor(Local<Name> name,
                     ^
../src/javaObject.cpp:116:47: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  v8::Local<v8::Object> javaObjectObj = ctor->NewInstance();
                                              ^
/Users/grin/.node-gyp/7.10.0/include/node/v8.h:3662:52: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                   ^
../src/javaObject.cpp:117:18: error: no member named 'SetHiddenValue' in 'v8::Object'
  javaObjectObj->SetHiddenValue(Nan::New<v8::String>(V8_HIDDEN_MARKER_JAVA_OBJECT).ToLocalChecked(), Nan::New<v8::Boolean>(true));
  ~~~~~~~~~~~~~  ^
../src/javaObject.cpp:349:47: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  v8::Local<v8::Object> javaObjectObj = ctor->NewInstance();
                                              ^
/Users/grin/.node-gyp/7.10.0/include/node/v8.h:3662:52: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                   ^
../src/javaObject.cpp:350:18: error: no member named 'SetHiddenValue' in 'v8::Object'
  javaObjectObj->SetHiddenValue(Nan::New<v8::String>(V8_HIDDEN_MARKER_JAVA_OBJECT).ToLocalChecked(), Nan::New<v8::Boolean>(true));
  ~~~~~~~~~~~~~  ^
5 warnings and 2 errors generated.
make: *** [Release/obj.target/nodejavabridge_bindings/src/javaObject.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/grin/message-classifier/node_modules/java
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
message-classifier@0.0.0 /Users/grin/message-classifier
└─┬ node-java@1.0.1 
  ├─┬ hessian-proxy@0.0.5 
  │ ├── buffer-builder@0.1.0 
  │ ├── buffer-reader@0.0.2 
  │ └── long@1.1.5 
  └─┬ node-zookeeper-client@0.2.2 
    ├── async@0.2.10 
    └── underscore@1.4.4 

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! java@0.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the java@0.7.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs java
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/grin/.npm/_logs/2017-05-30T16_21_33_902Z-debug.log
```

How can I fix this error?
Thanks a lot!

**Comment by TheShaperr** [comment]
Any update on this??

**Comment by mbejda** [comment]
Try downgrading node.js
