### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by DeepakDonde** [mbejda/Nodejs-Stanford-Classifier#9]
I tried to install package using getting started page but i am getting following error:

```
E:\Convee\StanfordDemo\corenlp_nodejs>npm install stanford-classifier --save

> java@0.7.2 install E:\Convee\StanfordDemo\corenlp_nodejs\node_modules\stanford-classifier\node_modules\java
> node-gyp rebuild


E:\Convee\StanfordDemo\corenlp_nodejs\node_modules\stanford-classifier\node_modules\java>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
[node-java] Error: Command failed: reg query "undefined" /v javahome
ERROR: Invalid key name.
Type "REG QUERY /?" for usage.

Error: Command failed: reg query "undefined" /v javahome
ERROR: Invalid key name.
Type "REG QUERY /?" for usage.

gyp: Call to 'node findJavaHome.js' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Convee\StanfordDemo\corenlp_nodejs\node_modules\stanford-classifier\node_modules\java
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\deepakd\AppData\Roaming\npm-cache\_logs\2019-03-29T06_53_08_553Z-debug.log
```

I have already installed `node-java` from [here](https://github.com/joeferner/node-java)

**Comment by mbejda** [comment]
I think it can't find Java. The compilation is failing when calling `findJavaHome.js . Please check the java node module repo for guidance.
